name: Install and build codebase
on:
  push:
    branches:
      - main

jobs:
  install_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: "Install packages"
        run: npm install
      - name: "Build codebase"
        run: npm run build